@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.nikdo53.tinymultiblocklib.block;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;