plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

base {
    archivesName = "${publish_name}-fabric-${minecraft_version}"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation "com.google.code.findbugs:jsr305:3.0.1"

    modCompileOnly("software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}")
    modCompileOnly "curse.maven:carry-on-274259:5649345"

    modLocalRuntime("software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}")
    modLocalRuntime "curse.maven:carry-on-274259:5649345"

    include(implementation("net.nikdo53:nikdo-color:1.0.0"))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "${publish_name}-fabric-${minecraft_version}"
        }
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
