plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.17-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.144' apply false
    id "me.modmuss50.mod-publish-plugin" version "2.2.0" apply false
}

subprojects {
    apply plugin: 'maven-publish'
    apply plugin: 'me.modmuss50.mod-publish-plugin'

    publishing {
        repositories {
            maven {
                url = "$rootDir/build/maven"
            }
        }
    }

    publishMods {
        type = STABLE
        version = project.version

        def changeLogFile = project.file("CHANGELOG.md")
        changelog = changeLogFile.exists() ? changeLogFile.text : ""
    }
}