# Project
version=4.0.0-beta2
group=net.nikdo53
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Tiny Multiblock Lib
mod_author=Nikdo53
mod_id=tinymultiblocklib
publish_name=tiny-multiblock-lib
license=MIT
credits=
description=A Tiny Lib for easy creation of Multiblocks, with a built-in ghost system. Usually packaged with other mods.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1.2-1

geckolib_version=5.4.5

# Fabric
fabric_version=0.158.0+26.1.2
fabric_loader_version=0.19.3

# Forge
neoforge_version=26.1.2.86
neoforge_loader_version_range=[4,)

# Config
config_api_version=26.1.5

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.configuration-cache=false

