plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly ("org.spongepowered:mixin:0.8.7")
    compileOnly(annotationProcessor('io.github.llamalad7:mixinextras-common:0.5.4'))

    compileOnly("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}"){transitive = false}
    compileOnly("curse.maven:carry-on-274259:4882500"){transitive = false}

    implementation("net.nikdo53:nikdo-color:1.0.0")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "${publish_name}-common-${minecraft_version}"
        }
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
