@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.nikdo53.tinymultiblocklib.color;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;